name: DBT
version: 1.0.0
config-version: 2
profile: DBT
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages
models:
  DBT:
    raw:
      +database: {{ databases.RAW }}
      +materialized: table
      

    transform:
      +database: {{ databases.TRANSFORM }}
      +materialized: table 

    consumption:
      +database: {{ databases.CONSUMPTION }}
      +materialized: table   
      +transient: false