DBT:
  target: {{ dbt_target }}
  outputs:
    dev:
      type: snowflake
      role: {{ snowflake_role }}
      warehouse: {{ warehouses.ELT }}
      database: {{ databases.TRANSFORM }}
      schema: {{ dbt_schema }}
      threads: 8

    prod:
      type: snowflake
      role: {{ snowflake_role }}
      warehouse: {{ warehouses.ELT }}
      database: {{ databases.TRANSFORM }}
      schema: {{ dbt_schema }}
      threads: 8
